
version: "3.7"
services:
  app:
    build:
      args:
        user: benose
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: irobot
    container_name: irobot-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - robot
  phpunit:
    image: irobot
    restart: unless-stopped
    volumes:
      - .:/var/www
    working_dir: /var/www
    entrypoint: vendor/bin/phpunit
networks:
  robot:
    driver: bridge
